#!/bin/bash

DATE=$(/usr/bin/date +%Y-%m-%d-%H:%M:%S)

BACKUP_DIR="/home/BackupsWebs" #CHANGE FOR YOU PERSONAL DIR

## IMPORTANT ## CHANGE TO THE NAME OF THE WEB DIRECTORY, IT MUST BE THE SAME AS THE NAME OF THE DATABASE ASSOCIATED TO THE WEB SITE.
WEBS=("web1"
      "web2") 

for web in ${WEBS[@]};do

      /usr/bin/mysqldump --user=MYSQL_USER --password=MYSQL_PASSWORD $web >$BACKUP_DIR/$web.sql

      if [ "$?" -eq 0 ]
      then
          echo -e "[$str] Mysqldump successfully finished at $(date +'%d-%m-%Y %H:%M:%S')"$'\r' >> "$BACKUP_DIR/backupLog-$DATE.txt"
      else
          echo -e "[$str] Mysqldump failed at $(date +'%d-%m-%Y %H:%M:%S')"$'\r' >> "$BACKUP_DIR/backupLog-$DATE.txt"
      fi
done

/usr/bin/tar -cvzpf $BACKUP_DIR/backup-$DATE.tar.gz /etc/apache2/ /var/www/html/ $BACKUP_DIR/*.sql $BACKUP_DIR/backupLog-$DATE.txt

for web in ${WEBS[@]};do
  /usr/bin/rm $BACKUP_DIR/$web.sql
done

/usr/bin/rm $BACKUP_DIR/backupLog-$DATE.txt
